name: Status Checks

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]
  workflow_dispatch:

jobs:
  tests:
    name: Evaluate on ${{ matrix.os }} with Godot ${{ matrix.godot_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        godot_version: [ '4.0.3', '4.1.0' ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: ${{ matrix.godot_version }}
          use-dotnet: false

      - name: Import files
        run: godot --editor --headless --quit --quiet
